spring:
  application:
    name: gateway
server:
  port: 9988
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8801/eureka/
zuul:
  routes:
    member:
      path: /api/member/**
      serverId: member
    game:
      path: /api/game/**
      serverId: game