spring:
  application:
    name: gateway
server:
  port: 9988

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7901/eureka/

zuul:
  ignored-services: configserver,monitor,ra,db         # 需要忽视的服务(配置后将不会被路由)
  # configserver-7701,monitor-7801,ra-7901
  # 这些项目只能运行一个：task-9001
  # db-9611
  routes:
    member:                   #9621    # 可以随便写，在zuul上面唯一即可
      path: /api/member/**                 # 想要映射到的路径
      serverId: member                # Eureka中的serviceId
    game:                     #9631
      path: /api/game/**
      serverId: game
#    notify:                   #9641
#      path: /notify/**
#      serverId: notify
#    rabbitmq:                 #9651
#      path: /rabbitmq/**
#      serverId: rabbitmq
#    file:                     #9661
#      path: /file/**
#      serverId: file
    album:                    #9671
      path: /api/album/**
      serverId: album
#    auth:                     #9681
#      path: /auth/**
#      serverId: auth
    php:                      #9691
      path: /api/php/**
      serverId: php
  host:
    max-total-connections: 500
    socket-timeout-millis: 30000
    connect-timeout-millis: 10000
